### ISSUE TITLE
Session date and time data is truncated in the session header

### ISSUE THREAD

**Issue by joshuacjx** [AY2021S1-CS2103-F09-1/tp#216]
The session date and time data for the session header is truncated.

**Screenshots**
<img width="454" alt="Screenshot 2020-11-07 at 4 52 01 PM" src="https://user-images.githubusercontent.com/59608088/98436828-999c7a00-2119-11eb-8acc-57dee2e226a3.png">

**Comment by sc-arecrow** [comment]
Closed by #213
