### ISSUE TITLE
Update Developer Guide

### ISSUE THREAD

**Issue by jaya-r3** [AY2021S1-CS2103-F09-1/tp#9]
1. **Target user profile, value proposition, and user stories**
1. **Use cases**
1. **Non-functional requirements**
1. **Glossary**

(W7 Task 4)

**Comment by sc-arecrow** [comment]
I will get on this issue as soon as I can!

**Comment by jaya-r3** [comment]
Breakdown of work:

@sc-arecrow:
As a TA, I can store the details of my students, so I can have quick access to them.
As a TA, I can view the details of a student, so I can have quick access to him/her.

@jayarengam:
As a TA, I can view the details of students, so I can have quick access to them.
As a TA, I can delete the details of students in my class, so I can still have quick access to them.
